# Generated by Django 3.1 on 2022-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
